<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap User Management Data Table</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="admin-style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <?php if (\Components\Auth::isAuth()) { ?>
                <div class="navbar-header">
                    <span class="navbar-brand" href="#"><?php echo \Components\Auth::getAuth()['username'] ?></span>
                </div>
            <?php } ?>
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/admin-profile">Submitted Forms</a></li>
                <li><a href="/admin-user">User Management</a></li>
                <li><a href="/logout" style="font-weight: 700!important">Logout</a></li>
            </ul>
        </div>
    </nav>
    <?php echo $this->content ?>
</div>
</body>
</html>