<form method="POST" class="register-form">
    <h2><?php echo !empty($this->params['id']) ? 'Edit' : 'Create' ?> User</h2>
    <input type="hidden" name='id' value="<?php echo isset($this->params['id']) ? $this->params['id'] : '' ?>">
    <div class="form-group <?php echo (!empty($this->errors['username'])) ? 'has-error' : ''; ?>">
        <label>Username</label>
        <input type="text" name="name" class="form-control" required
               value="<?php echo isset($this->params['name']) ? $this->params['name'] : '' ?>">
        <?php if (!empty($this->errors['name'])) { ?>
            <span class="help-block"><?php echo $this->errors['name'] ?></span>
        <?php } ?>
    </div>
    <div class="form-group <?php echo (!empty($this->errors['email'])) ? 'has-error' : ''; ?>">
        <label>Email</label>
        <input type="email" name="email" class="form-control" required
               value="<?php echo isset($this->params['email']) ? $this->params['email'] : '' ?>">
        <?php if (!empty($this->errors['email'])) { ?>
            <span class="help-block"><?php echo $this->errors['email'] ?></span>
        <?php } ?>
    </div>
    <div class="form-group <?php echo (!empty($this->errors['department'])) ? 'has-error' : ''; ?>">
        <label>Department</label>
        <input type="text" name="department" class="form-control" required
               value="<?php echo isset($this->params['department']) ? $this->params['department'] : '' ?>">
        <?php if (!empty($this->errors['department'])) { ?>
            <span class="help-block"><?php echo $this->errors['department'] ?></span>
        <?php } ?>
    </div>

    <?php if (!isset($this->params['id']) || $this->params['id'] != 1): ?>
        <div class="form-group">
            <label>Role</label>
            <select name="role" class="form-control" style="height: 30px" required>
                <option>user</option>
                <option <?php echo ($this->params['role'] == 'admin') ? 'selected="selected"' : '' ?>>admin</option>
            </select>
        </div>
    <?php endif; ?>
    <div class="form-group <?php echo (!empty($this->errors['password'])) ? 'has-error' : ''; ?>">
        <label>Password</label>
        <input type="password" name="password" class="form-control" required minlength="6">
        <?php if (!empty($this->errors['password'])) { ?>
            <span class="help-block"><?php echo $this->errors['password']; ?></span>
        <?php } ?>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Submit">
    </div>
    <p>Already have an account? <a href="login.php">Login here</a>.</p>
</form>