<div class="table-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-5">
                <h2>Submitted <b>Forms</b></h2>
            </div>
        </div>
    </div>
    <form method="POST">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th></th>
                <th width="20%">Created</th>
                <th width="20%">Edited</th>
                <th width="15%">Name</th>
                <th width="20%">Department</th>
                <th width="20%">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($this->forms)) { ?>
                <?php foreach ($this->forms as $form) { ?>
                    <tr>
                        <td>
                            <div class="form-check">
                                <input type="checkbox" name="ids[]" value="<?php echo $form['id'] ?>" class="form-check-input"
                                       id="exampleCheck1">
                            </div>
                        </td>
                        <td><?php echo $form['date_added'] ?></td>
                        <td><?php echo $form['date_edited'] !== $form['date_added'] ? $form['date_edited'] : '-' ?></td>
                        <td><?php echo $form['name'] ?></td>
                        <td><?php echo $form['department'] ?></td>
                        <td>
                            <a href="/calculator/form?id=<?php echo $form['id'] ?>">View</a>

                            /

                            <a href="/calculator/excel?id=<?php echo $form['id'] ?>">Save in Excel</a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="3">Not submitted forms.</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <div class="form-group">
            <input class="btn btn-primary" value="Save to archive" type="submit">
        </div>
    </form>
</div>
