<div class="table-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-5">
                <h2>User <b>Management</b></h2>
            </div>
            <div class="col-sm-7">
                <a href="/admin-user?action=create" class="btn btn-primary"><i class="material-icons">&#xE147;</i>
                    <span>Add New User</span></a>
            </div>
        </div>
    </div>
    <? foreach ($this->errors as $error) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <? endforeach; ?>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->users as $user): ?>
            <tr>
                <td><?= $user['id'] ?></td>
                <td><a href="#"><?= $user['name'] ?></a></td>
                <td><a href="#"><?= $user['email'] ?></a></td>
                <td><?= $user['department'] ?></td>
                <td><?= $user['role'] ?></td>
                <td>
                    <a href="/admin-user?action=edit&id=<?= $user['id'] ?>" class="settings" title="Settings"
                       data-toggle="tooltip"><i
                                class="material-icons">&#xE8B8;</i></a>
                    <a href="javascript:;"
                       data-href="/admin-user?action=delete&id=<?= $user['id'] ?>" class="delete delete-user"
                       title="Delete"
                       data-toggle="tooltip"><i
                                class="material-icons">&#xE5C9;</i></a>
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>
</div>
</div>

<script>
    $(document).ready(function () {
        $('.delete-user').on('click', function () {
            var href = $(this).data('href');

            if (confirm('Are you sure?')) {
                location.href = href;
            }
        });
    });
</script>