<? for ($i = 1; $i <= 6; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>

            <? if ($i === 4) { ?>
                <br><br>
                <? for ($j = 1; $j <= 4; $j++) { ?>
                    <div style="margin-left: 50px;">sub item 4_<?= $j ?></div>
                <? } ?>
            <? } ?>
        </td>
        <td>
            <?= HTMLElements::input("category_2_description_{$i}") ?>
        </td>
        <td>
            <?= HTMLElements::input("category_2_value_{$i}_1") ?>
        </td>
        <td>
            <?= HTMLElements::input("category_2_value_{$i}_2") ?>
        </td>
        <td>
            <?= HTMLElements::input("category_2_value_{$i}_3") ?>
        </td>
    </tr>
<? } ?>
<tr>
    <td colspan="2">
        <b>Category 3</b>
    </td>
    <td>0</td>
    <td>0</td>
    <td>0</td>
</tr>