<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container" style="margin-top: 20px;">
    <style>
        .table th:nth-child(1) {
            width: 40%;
        }

        .table th:nth-child(2) {
            width: 30%;
        }

        .table th:nth-child(3),
        .table th:nth-child(4),
        .table th:nth-child(5) {
            width: 10%;
        }

        .table .form-group {
            margin: 0px;
        }
    </style>
    <table class="table table-bordered" style="max-width: 1000px;">
        <thead>
        <tr>
            <th>Description</th>
            <th>Details</th>
            <th>Year 1</th>
            <th>Year 2</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
            <?= Renderer::partial('templates/category-a.phtml') ?>
            <?= Renderer::partial('templates/category-b.phtml') ?>
            <?= Renderer::partial('templates/category-1.phtml') ?>
            <?= Renderer::partial('templates/category-2.phtml') ?>
            <?= Renderer::partial('templates/category-3.phtml') ?>
            <?= Renderer::partial('templates/category-4.phtml') ?>
        </tbody>
    </table>
</div>
</body>
</html>