<form method="POST">
    <?php echo Renderer::factory('templates/table/description', $this)->render() ?>

    <table id="table-form" class="table table-bordered header-green">
        <?php echo Renderer::factory('templates/table/header', $this)->render() ?>
        <tbody>
        <?php echo Renderer::factory('templates/table/category-1', $this)->render() ?>

        <?php echo Renderer::factory('templates/table/header', $this)->render() ?>
        <?php echo Renderer::factory('templates/table/category-2', $this)->render() ?>

        <?php echo Renderer::factory('templates/table/header', $this)->render() ?>
        <?php echo Renderer::factory('templates/table/category-3', $this)->render() ?>

        <?php echo Renderer::factory('templates/table/header', $this)->render() ?>
        <?php echo Renderer::factory('templates/table/category-4', $this)->render() ?>

        <?php echo Renderer::factory('templates/table/header', $this)->render() ?>
        <?php echo Renderer::factory('templates/table/category-5', $this)->render() ?>

        <?php echo Renderer::factory('templates/table/header', $this)->render() ?>
        <?php echo Renderer::factory('templates/table/category-6', $this)->render() ?>

        <tr>
            <td colspan="5">
                <?php if (empty($this->data['submitted'])) { ?>
                    <input type="submit" value="Calculate">
                    <input type="submit" value="Save to data base" name="saveToDb">
                    <input type="submit" value="Submit" name="submit">
                <?php } ?>
                <input type="submit" value="Save to XML" name="saveToXML">
            </td>
        </tr>
        </tbody>
    </table>

    <script>
        $('#table-form').find('input[name^=d], input[name^=e]').numeric({
            decimal: false,
            negative: false,
            decimalPlaces: -1
        });

        $(document).ready(function () {
            var jqxhr = null;

            $('#table-form').find('input[name^=d], input[name^=e]').on('keyup', function () {
                var formData = $('#table-form').closest('form').serialize(),
                    $section = $(this).closest('tbody:not(.inner-body)'),
                    total = ['d72', 'e72', 'f72'];

                if (jqxhr) {
                    jqxhr.abort();
                }

                jqxhr = $.ajax({
                    url: '/form',
                    type: 'POST',
                    data: formData,
                    success: function (response) {
                        if (response !== null && typeof(response) === 'object') {
                            $section.find('.result').each(function () {
                                var $elem = $(this),
                                    id = $elem.attr('id');

                                if (id in response) {
                                    $elem.html('<b>' + response[id] + '</b>');
                                }
                            });

                            $.each(total, function(i, elem){
                                if (elem in response) {
                                    $('#' + elem).html('<b>' + response[elem] + '</b>');
                                }
                            });
                        }
                    },
                    complete: function () {
                        jqxhr = null;
                    }
                });
            });
        });

    </script>
</form>