<form method="POST">
    <?= Renderer::factory('templates/table/description', $this)->render() ?>

    <table id="table-form" class="table table-bordered">
        <?= Renderer::factory('templates/table/header', $this)->render() ?>
        <tbody>
        <?= Renderer::factory('templates/table/category-1', $this)->render() ?>

        <?= Renderer::factory('templates/table/header', $this)->render() ?>
        <?= Renderer::factory('templates/table/category-2', $this)->render() ?>

        <?= Renderer::factory('templates/table/header', $this)->render() ?>
        <?= Renderer::factory('templates/table/category-3', $this)->render() ?>

        <?= Renderer::factory('templates/table/header', $this)->render() ?>
        <?= Renderer::factory('templates/table/category-4', $this)->render() ?>

        <?= Renderer::factory('templates/table/header', $this)->render() ?>
        <?= Renderer::factory('templates/table/category-5', $this)->render() ?>

        <?= Renderer::factory('templates/table/header', $this)->render() ?>
        <?= Renderer::factory('templates/table/category-6', $this)->render() ?>

        <tr>
            <td colspan="5">
                <? if (empty($this->data['submitted'])) { ?>
                    <input type="submit" value="Calculate">
                    <input type="submit" value="Save to data base" name="saveToDb">
                    <input type="submit" value="Submit" name="submit">
                <? } ?>
                <input type="submit" value="Save to XML" name="saveToXML">
            </td>
        </tr>
        </tbody>
    </table>

    <script>
        $('#table-form').find('input[name^=d], input[name^=e]').numeric({
            decimal: false,
            negative: false,
            decimalPlaces: -1
        });
    </script>
</form>