<table class="table table-bordered profile-users-forms">
    <thead>
    <th>Created</th>
    <th>Edited</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <?php if (count($this->forms)) { ?>
        <?php foreach ($this->forms as $form) { ?>
            <tr>
                <td><?php echo $form['date_added'] ?></td>
                <td><?php echo $form['date_edited'] !== $form['date_added'] ? $form['date_edited'] : '-' ?></td>
                <td><a href="/form?id=<?php echo $form['id'] ?>">Edit or view</a></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="3">You don't have saved or submitted forms.</td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<input id="add-new-form" type="button" value="Add" onclick="location.href='/calculator/form'">