<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="jquery.numeric.min.js"></script>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <? if (\Components\Auth::isAuth()) { ?>
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><?= \Components\Auth::getAuth()['username'] ?></a>
                </div>
            <? } ?>
            <ul class="nav navbar-nav">
                <? if (\Components\Auth::isAuth()) : ?>
                    <li><a href="/">Home</a></li>
                <? endif; ?>
                <? if (\Components\Auth::isAdmin()): ?>
                    <li><a href="/admin-profile">Admin Profile</a></li>
                    <li><a href="/admin-user">User Management</a></li>
                <? endif ?>
                <? if (\Components\Auth::isAuth()) : ?>
                    <li><a href="/logout" style="font-weight: 700!important">Logout</a></li>
                <? endif; ?>
            </ul>
        </div>
    </nav>
    <?= $this->content ?>
</div>
</body>
</html>