<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
<header>
    <? if (\Components\Auth::isAuth()) { ?>
        <div class="auth-info">
            <span class="username"><?= \Components\Auth::getAuth()['username'] ?></span>
            <span class="logout"><a href="/logout">Logout</a></span>
        </div>
    <? } ?>
</header>
<?= $this->content ?>
</div>
</body>
</html>