<style type="text/css">
    .wrapper {
        width: 350px;
        padding: 20px;
    }
</style>

<form method="POST" class="form-auth">
    <h2>Login</h2>
    <p>Please fill in your credentials to login.</p>

    <div class="form-group <?php echo (!empty($this->errors['email'])) ? 'has-error' : ''; ?>">
        <label>Email</label>
        <input type="text" name="email" class="form-control" value="<?php echo $this->email; ?>">
        <?php if (!empty($this->errors['email'])) { ?>
            <span class="help-block"><?php echo $this->errors['email']; ?></span>
        <?php } ?>
    </div>
    <div class="form-group <?php echo (!empty($this->errors['password'])) ? 'has-error' : ''; ?>">
        <label>Password</label>
        <input type="password" name="password" class="form-control">
        <?php if (!empty($this->errors['password'])) { ?>
            <span class="help-block"><?php echo $this->errors['password']; ?></span>
        <?php } ?>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Login">
    </div>
    <p>Don't have an account? <a href="/calculator/register">Sign up now</a>.</p>
</form>
