<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <form method="POST">
        <?= Renderer::factory('templates/table/description', $this)->render() ?>

        <table class="table table-bordered">
            <?= Renderer::factory('templates/table/header', $this)->render() ?>
            <tbody>
            <?= Renderer::factory('templates/table/category-1', $this)->render() ?>

            <?= Renderer::factory('templates/table/header', $this)->render() ?>
            <?= Renderer::factory('templates/table/category-2', $this)->render() ?>

            <?= Renderer::factory('templates/table/header', $this)->render() ?>
            <?= Renderer::factory('templates/table/category-3', $this)->render() ?>

            <?= Renderer::factory('templates/table/header', $this)->render() ?>
            <?= Renderer::factory('templates/table/category-4', $this)->render() ?>

            <?= Renderer::factory('templates/table/header', $this)->render() ?>
            <?= Renderer::factory('templates/table/category-5', $this)->render() ?>

            <?= Renderer::factory('templates/table/header', $this)->render() ?>
            <?= Renderer::factory('templates/table/category-6', $this)->render() ?>
            </tbody>
        </table>
        <input type="submit" value="Calculate">
        <input type="submit" value="Save to XML" name="saveToXML">
    </form>
</div>
</body>
</html>