<?php for ($row = 64; $row <= 68; $row++) { ?>
    <tr>
        <td><?php echo \HTMLElements::label("b{$row}", $this->labels) ?></td>
        <td><?php echo HTMLElements::textarea("c{$row}", $this->data); ?></td>
        <td style="vertical-align:middle">
            <?php echo HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td style="vertical-align:middle"><?php echo HTMLElements::input("e{$row}", $this->data) ?></td>
        <td style="vertical-align:middle"><?php echo HTMLElements::result("f{$row}", $this->data) ?></td>
    </tr>
<?php } ?>

<tr>
    <td colspan="2">
        <b>Total (<?php echo \HTMLElements::label("b70", $this->labels) ?>)</b>
    </td>
    <td><?php echo HTMLElements::result('d70', $this->data) ?></td>
    <td><?php echo HTMLElements::result('e70', $this->data) ?></td>
    <td><?php echo HTMLElements::result('f70', $this->data) ?></td>
</tr>

<tr class="grand-total-row">
    <td colspan="2">
        <b>Grand Total</b>
    </td>
    <td><?php echo HTMLElements::result('d72', $this->data) ?></td>
    <td><?php echo HTMLElements::result('e72', $this->data) ?></td>
    <td><?php echo HTMLElements::result('f72', $this->data) ?></td>
</tr>