<? for ($i = 1; $i <= 4; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>
        </td>
        <td>
            <?= HTMLElements::input("category_0_description_{$i}_1", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("category_0_value_{$i}_1", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("category_0_value_{$i}_2", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("category_0_value_{$i}_3", $this->data) ?>
        </td>
    </tr>
<? } ?>
<tr>
    <td colspan="3"></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
</tr>
<tr>
    <td colspan="2">
        <b>Total amount</b>
    </td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
</tr>