<? $row = 31; ?>



<? for ($i = 1; $i <= 4; $i++) { ?>
    <tr>
        <td>
            <?
            switch ($i){
                case 1:
                    echo 'Subcontracts (>100K AED)';
                    break;
                case 2:
                    echo 'Subcontracts (<100K AED)';
                    break;
                default:
                    echo 'Item ' . $i;
            }
            ?>
        </td>
        <td>
            <? if ($i < 3) { ?>
                <?= HTMLElements::input("category_2_description_{$i}", $this->data, ['placeholder' => '[name of subawrdee]']) ?><br>
            <? } ?>
        </td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("f{$row}", $this->data) ?>
        </td>

        <? $row++; ?>
    </tr>
<? } ?>
<tr>
    <td colspan="2">
        <b>Category 2</b>
    </td>
    <td><?= HTMLElements::result('d36', $this->data) ?></td>
    <td><?= HTMLElements::result('e36', $this->data) ?></td>
    <td><?= HTMLElements::result('f36', $this->data) ?></td>
</tr>