<? $row = 61; ?>

<? for ($i = 1; $i <= 5; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>
        </td>
        <td></td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td>
            <? if ("f{$row}" === 'f61' || "f{$row}" === 'f62' || "f{$row}" === 'f63' || "f{$row}" === 'f64' || "f{$row}" === 'f65') { ?>
                <?= HTMLElements::result("f{$row}", $this->data) ?>
            <? } else { ?>
                <?= HTMLElements::input("f{$row}", $this->data) ?>
            <? } ?>
        </td>
    </tr>

    <? $row++; ?>
<? } ?>
<tr>
    <td colspan="2">
        <b>Total category 4</b>
    </td>
    <td><?= HTMLElements::result('d67', $this->data) ?></td>
    <td><?= HTMLElements::result('e67', $this->data) ?></td>
    <td><?= HTMLElements::result('f67', $this->data) ?></td>
</tr>
<tr>
    <td colspan="2">
        <b>Subtotal Direct Costs</b>
    </td>
    <td><?= HTMLElements::result('d68', $this->data) ?></td>
    <td><?= HTMLElements::result('e68', $this->data) ?></td>
    <td><?= HTMLElements::result('f68', $this->data) ?></td>
</tr>
<tr>
    <td colspan="2">
        <b>Subtotal other costs </b>
    </td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
</tr>
<tr>
    <td colspan="2">
        <b>TOTAL COSTS</b>
    </td>
    <td><?= HTMLElements::result('d70', $this->data) ?></td>
    <td><?= HTMLElements::result('e70', $this->data) ?></td>
    <td><?= HTMLElements::result('f70', $this->data) ?></td>
</tr>