<? for ($i = 1; $i <= 7; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>
        </td>
        <td>
            <?= HTMLElements::input("category_4_description_{$i}", $this->data) ?><br>
        </td>
        <td>
            <?= HTMLElements::input("category_4_value_{$i}_1", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("category_4_value_{$i}_2", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("category_4_value_{$i}_3", $this->data) ?>
        </td>

    </tr>
<? } ?>
<tr>
    <td colspan="2">
        <b>Category 4</b>
    </td>
    <td>0</td>
    <td>0</td>
    <td>0</td>
</tr>