<? $row = 38; ?>

<? for ($i = 1; $i <= 6; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>

            <? if ($i === 4) { ?>
                <br><br>
                <? for ($j = 1; $j <= 4; $j++) { ?>
                    <div style="margin-left: 50px;">sub item 4_<?= $j ?></div>
                <? } ?>
            <? } ?>
        </td>
        <td></td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td>
            <? if ("f{$row}" === 'f38' || "f{$row}" === 'f39' || "f{$row}" === 'f40') { ?>
                <?= HTMLElements::result("f{$row}", $this->data) ?>
            <? } else { ?>
                <?= HTMLElements::input("f{$row}", $this->data) ?>
            <? } ?>
        </td>
        <? if ($i === 4) { ?>
            <? $row += 4; ?>
        <? } ?>
    </tr>

    <? $row++; ?>
<? } ?>
<tr>
    <td colspan="2">
        <b>Category 3</b>
    </td>
    <td><?= HTMLElements::result('d49', $this->data) ?></td>
    <td><?= HTMLElements::result('e49', $this->data) ?></td>
    <td><?= HTMLElements::result('f49', $this->data) ?></td>
</tr>