<? $row = 38;
$isSubRow = false; ?>

<? for ($i = 1; $i <= 6; $i++) { ?>
    <?
    if ($i === 4) {
        echo Renderer::factory('templates/table/category-3-sub', $this)->render();
        continue;
    }
    ?>
    <tr>
        <td>Label</td>
        <td><?= HTMLElements::input("category_3_description_{$i}", $this->data) ?></td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td><?= HTMLElements::result("f{$row}", $this->data) ?></td>
        <? if ($i === 4) { ?>
            <? $row += 4; ?>
        <? } ?>
    </tr>

    <? $row++; ?>
<? } ?>
<tr>
    <td colspan="2">
        <b>Category 3</b>
    </td>
    <td><?= HTMLElements::result('d49', $this->data) ?></td>
    <td><?= HTMLElements::result('e49', $this->data) ?></td>
    <td><?= HTMLElements::result('f49', $this->data) ?></td>
</tr>