<? for ($row = 54; $row <= 60; $row++) { ?>
    <tr>
        <td><?= \HTMLElements::label("b{$row}", $this->labels) ?></td>
        <td><?= HTMLElements::textarea("c{$row}", $this->data); ?></td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td><?= HTMLElements::input("e{$row}", $this->data) ?></td>
        <td><?= HTMLElements::result("f{$row}", $this->data) ?></td>
    </tr>
<? } ?>

<tr>
    <td colspan="2">
        <b>Total (label)</b>
    </td>
    <td><?= HTMLElements::result('d62', $this->data) ?></td>
    <td><?= HTMLElements::result('e62', $this->data) ?></td>
    <td><?= HTMLElements::result('f62', $this->data) ?></td>
</tr>