<? for ($row = 9; $row <= 12; $row++) { ?>
    <tr>
        <td colspan="5" class="with-table">
            <table style="width:100%" class="table table-bordered borderless">
                <tbody class="inner-body">
                <tr>
                    <td style="vertical-align:middle; width:20%"><?= \HTMLElements::label("b{$row}", $this->labels) ?></td>
                    <td style="vertical-align:middle; width:50%">
                        <?= HTMLElements::textarea("c{$row}", $this->data) ?>
                    </td>
                    <td style="vertical-align:middle; width:10%">
                        <?= HTMLElements::input("d{$row}", $this->data) ?>
                    </td>
                    <td style="vertical-align:middle; width:10%"><?= HTMLElements::input("e{$row}", $this->data) ?></td>
                    <td style="vertical-align:middle; width:10%"><?= HTMLElements::result("f{$row}", $this->data) ?></td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
<? } ?>

<tr>
    <td colspan="2">
        <b>Total (<?= \HTMLElements::label("b14", $this->labels) ?>)</b>
    </td>
    <td><?= HTMLElements::result('d14', $this->data) ?></td>
    <td><?= HTMLElements::result('e14', $this->data) ?></td>
    <td><?= HTMLElements::result('f14', $this->data) ?></td>
</tr>