<? $row = 9; ?>

<? for ($i = 1; $i <= 4; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>
        </td>
        <td>
            <?= HTMLElements::input("category_0_description_{$i}_1", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("f{$row}", $this->data) ?>
        </td>
    </tr>

    <? $row++; ?>
<? } ?>
<tr>
    <td colspan="3"></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
</tr>
<tr>
    <td colspan="2">
        <b>Total amount</b>
    </td>
    <td><?= HTMLElements::result('d14', $this->data) ?></td>
    <td><?= HTMLElements::result('e14', $this->data) ?></td>
    <td><?= HTMLElements::result('f14', $this->data) ?></td>
</tr>