<? $row = 51; ?>

<? for ($i = 1; $i <= 7; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>
        </td>
        <td>
            <?= HTMLElements::input("category_4_description_{$i}", $this->data) ?><br>
        </td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("f{$row}", $this->data) ?>
        </td>

        <? $row++; ?>
    </tr>
<? } ?>
<tr>
    <td colspan="2">
        <b>Category 4</b>
    </td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
</tr>