<? $b = 16;
$c = $d = $e = $f = 17; ?>

<? for ($i = 1; $i <= 3; $i++) { ?>
    <tr class="">
        <td colspan="5"><?= \HTMLElements::label("b{$b}", $this->labels) ?></td>
    </tr>
    <tr>
        <td colspan="5" class="with-table">
            <table class="table table-bordered borderless" style="width: 100%;">
                <tbody class="inner-body">
                <?
                $j = 3;
                while ($j--) { ?>
                    <tr>
                        <td width="20%"></td>
                        <td width="50%">
                            <?= HTMLElements::textarea("c{$c}", $this->data) ?>
                        </td>
                        <td width="10%">
                            <?= HTMLElements::input("d{$d}", $this->data) ?>
                        </td>
                        <td width="10%">
                            <?= HTMLElements::input("e{$e}", $this->data) ?>
                        </td>
                        <td width="10%">
                            <?= HTMLElements::result("f{$f}", $this->data) ?>
                        </td>
                    </tr>
                    <?
                    $c++;
                    $d++;
                    $e++;
                    $f++;
                    ?>
                <? } ?>
                </td>
                </tbody>
            </table>
        </td>
    </tr>
    <tr class="sub-row">
        <? $b += 4; ?>
        <td colspan="2">Total (<?= \HTMLElements::label("b{$b}", $this->labels) ?>)</td>
        <td class="d<?= $d ?>"><?= HTMLElements::result("d{$d}", $this->data) ?></td>
        <td class="e<?= $e ?>"><?= HTMLElements::result("e{$e}", $this->data) ?></td>
        <td class="f<?= $f ?>"><?= HTMLElements::result("f{$f}", $this->data) ?></td>
        <? $d++;
        $c++;
        $e++;
        $f++; ?>
    </tr>

    <?
    $b++;
    $c++;
    $d++;
    $e++;
    $f++;
    ?>
<? } ?>
<tr>
    <td colspan="2">
        <b>Total (<?= \HTMLElements::label("b32", $this->labels) ?>)</b>
    </td>
    <td><?= HTMLElements::result('d32', $this->data) ?></td>
    <td><?= HTMLElements::result('e32', $this->data) ?></td>
    <td><?= HTMLElements::result('f32', $this->data) ?></td>
</tr>
