<? $row = 61; ?>

<? for ($i = 1; $i <= 5; $i++) { ?>
    <tr>
        <td>
            Item <?= $i ?>
        </td>
        <td>
            <?= HTMLElements::input("category_4_total_description_{$i}", $this->data) ?><br>
        </td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("f{$row}", $this->data) ?>
        </td>
    </tr>

    <? $row++; ?>
<? } ?>
<tr>
    <td colspan="2">
        <b>Total category 4</b>
    </td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
    <td><?= HTMLElements::result('', $this->data) ?></td>
</tr>