<? for ($row = 64; $row <= 68; $row++) { ?>
    <tr>
        <td colspan="5" class="with-table">
            <table class="table table-bordered borderless" style="width: 100%;">
                <tbody class="inner-body">
                <td style="vertical-align:middle; width:20%"><?= \HTMLElements::label("b{$row}", $this->labels) ?></td>
                <td style="vertical-align:middle; width:50%"><?= HTMLElements::textarea("c{$row}", $this->data); ?></td>
                <td style="vertical-align:middle; width:10%">
                    <?= HTMLElements::input("d{$row}", $this->data) ?>
                </td>
                <td style="vertical-align:middle; width:10%"><?= HTMLElements::input("e{$row}", $this->data) ?></td>
                <td style="vertical-align:middle; width:10%"><?= HTMLElements::result("f{$row}", $this->data) ?></td>
                </tbody>
            </table>
        </td>

    </tr>
<? } ?>

<tr>
    <td colspan="2">
        <b>Total (<?= \HTMLElements::label("b70", $this->labels) ?>)</b>
    </td>
    <td><?= HTMLElements::result('d70', $this->data) ?></td>
    <td><?= HTMLElements::result('e70', $this->data) ?></td>
    <td><?= HTMLElements::result('f70', $this->data) ?></td>
</tr>

<tr class="grand-total-row">
    <td colspan="2">
        <b>Grand Total</b>
    </td>
    <td><?= HTMLElements::result('d72', $this->data) ?></td>
    <td><?= HTMLElements::result('e72', $this->data) ?></td>
    <td><?= HTMLElements::result('f72', $this->data) ?></td>
</tr>