<? $i = 4; $row =45; ?>
<? while ($i--) { ?>
    <tr class="category-3-sub-row">
        <td>Sublabel</td>
        <td><?= HTMLElements::input("category_3_description_{$i}", $this->data) ?></td>
        <td>
            <?= HTMLElements::input("d{$row}", $this->data) ?>
        </td>
        <td>
            <?= HTMLElements::input("e{$row}", $this->data) ?>
        </td>
        <td><?= HTMLElements::result("f{$row}", $this->data) ?></td>
        <? if ($i === 4) { ?>
            <? $row += 4; ?>
        <? } ?>
    </tr>
<? } ?>