<? $row = 41; ?>

<? for ($i = 1; $i <= 6; $i++) { ?>
    <?
    if ($i === 4) {
        echo Renderer::factory("templates/table/category-4-sub", $this)->render();
        $row += 5;
        continue;
    }
    ?>
    <tr>
        <td colspan="5" class="with-table">
            <table style="width:100%" class="table table-bordered borderless">
                <tbody class="inner-body">
                <tr>
                    <td style="vertical-align:middle; width:20%"><?= \HTMLElements::label("b{$row}", $this->labels) ?></td>
                    <td style="vertical-align:middle; width:50%"><?= HTMLElements::textarea("c{$row}", $this->data) ?></td>
                    <td style="vertical-align:middle; width:10%">
                        <?= HTMLElements::input("d{$row}", $this->data) ?>
                    </td>
                    <td style="vertical-align:middle; width:10%">
                        <?= HTMLElements::input("e{$row}", $this->data) ?>
                    </td>
                    <td style="vertical-align:middle; width:10%"><?= HTMLElements::result("f{$row}", $this->data) ?></td>
                    <? if ($i === 4) { ?>
                        <? $row += 4; ?>
                    <? } ?>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>

    <? $row++; ?>
<? } ?>
<tr>
    <td colspan="2">
        <b>Total (label)</b>
    </td>
    <td><?= HTMLElements::result('d52', $this->data) ?></td>
    <td><?= HTMLElements::result('e52', $this->data) ?></td>
    <td><?= HTMLElements::result('f52', $this->data) ?></td>
</tr>