<?
$c = [
    1 => ['position' => 'c2', 'title' => 'Proposal Budget'],
    2 => ['position' => 'c3', 'title' => 'Program'],
    3 => ['position' => 'c4', 'title' => 'Sponsor'],
];
$e = [
    1 => ['position' => 'e2', 'title' => 'PI'],
    2 => ['position' => 'e3', 'title' => 'Co-I'],
    3 => ['position' => 'e4', 'title' => 'Period'],
];
?>

<?php $i = 1;
$j = 4;
$rows = 3; ?>

<table class="table table-bordered table-description header-green">
    <thead>
    <tr>
        <th colspan="2">Image</th>
    </tr>
    </thead>
    <tbody>
    <?php for ($row = 1; $row <= $rows; $row++) { ?>
        <tr>
            <td>
                <span><?php echo $c[$row]['title'] ?></span>
                <?php echo HTMLElements::textarea($c[$row]['position'], $this->data) ?>
            </td>
            <td>
                <span><?php echo $e[$row]['title'] ?></span>
                <?php echo HTMLElements::textarea($e[$row]['position'], $this->data) ?>
            </td>
        </tr>

        <?php $i++;
        $j++; ?>
    <?php } ?>
    </tbody>
</table>